services:
  arch:
    build:
      dockerfile: Dockerfile.arch
    environment:
      - TERM=xterm-256color
      - UV_CACHE_DIR=/tmp/.cache/uv
      - UV_PROJECT_ENVIRONMENT=/tmp/.venv
    stdin_open: true
    tty: true
    working_dir: /home/user
    volumes:
      - ./cli:/home/user/.dotfiles/cli
      - ./os:/home/user/.dotfiles/os
      - ./src:/home/user/.dotfiles/src
      - ./install:/home/user/.dotfiles/install
      - ./main.py:/home/user/.dotfiles/main.py
      - ./project.json:/home/user/.dotfiles/project.json
      - ./pyproject.toml:/home/user/.dotfiles/pyproject.toml
      - ./uv.lock:/home/user/.dotfiles/uv.lock
    tmpfs:
      - /home/user/.dotfiles/.build:uid=1000,gid=1000,exec
    command: bash -c "sleep infinity"
