[project]
version = "0.0.0"
name = "dotfiles-next"
description = "My personal dotfiles"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "dataclasses-json>=0.6.7",
    "rich>=14.0.0",
]

[tool.uv.workspace]
members = [
    "cli/python",
]
