# Linux OS config
[window]
option_as_alt = 'Both'
dimensions = { columns = 80, lines = 24 }
opacity = 1

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
bold = { family = "MesloLGS NF", style = "Bold" }
italic = { family = "MesloLGS NF", style = "Italic" }

[colors]
# Default colors
[colors.primary]
background = "0x1f1f28"
foreground = "0xdcd7ba"

# Cursor colors
[colors.cursor]
text = "0x1f1f28"
cursor = "0xc8c093"

# Normal colors
[colors.normal]
black = "0x1f1f28"
red = "0xc34043"
green = "0x76946a"
yellow = "0xc0a36e"
blue = "0x7e9cd8"
magenta = "0x957fb8"
cyan = "0x6a9589"
white = "0xc8c093"

# Bright colors
[colors.bright]
black = "0x727169"
red = "0xe82424"
green = "0x98bb6c"
yellow = "0xe6c384"
blue = "0x7fb4ca"
magenta = "0x938aa9"
cyan = "0x7aa89f"
white = "0xdcd7ba"

# Dim colors
[colors.dim]
black = "0x1f1f28"
red = "0xc34043"
green = "0x76946a"
yellow = "0xc0a36e"
blue = "0x7e9cd8"
magenta = "0x957fb8"
cyan = "0x6a9589"
white = "0xc8c093"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "W"
mods = "Control|Shift"
action = "Quit"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"
