[project]
name = "cli"
version = "0.1.0"
description = "Python-based dotfiles CLI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
]

[tool.uv]
env-file = ".env.local"
